### ISSUE TITLE
can not connect to ubuntu 14.0.4

### ISSUE THREAD

**Issue by K0zka** [kerubistan/kerub#138]
```
Caused by: org.apache.sshd.common.SshException: No more authentication methods available
	at org.apache.sshd.client.session.ClientUserAuthService.tryNext(ClientUserAuthService.java:315) ~[sshd-core-1.2.0.jar:1.2.0]
	at org.apache.sshd.client.session.ClientUserAuthService.processUserAuth(ClientUserAuthService.java:252) ~[sshd-core-1.2.0.jar:1.2.0]
	at org.apache.sshd.client.session.ClientUserAuthService.process(ClientUserAuthService.java:199) ~[sshd-core-1.2.0.jar:1.2.0]
	at org.apache.sshd.common.session.helpers.AbstractSession.doHandleMessage(AbstractSession.java:530) ~[sshd-core-1.2.0.jar:1.2.0]
	at org.apache.sshd.common.session.helpers.AbstractSession.handleMessage(AbstractSession.java:463) ~[sshd-core-1.2.0.jar:1.2.0]
	at org.apache.sshd.common.session.helpers.AbstractSession.decode(AbstractSession.java:1325) ~[sshd-core-1.2.0.jar:1.2.0]
	at org.apache.sshd.common.session.helpers.AbstractSession.messageReceived(AbstractSession.java:424) ~[sshd-core-1.2.0.jar:1.2.0]
	at org.apache.sshd.common.session.helpers.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:67) ~[sshd-core-1.2.0.jar:1.2.0]
	at org.apache.sshd.common.io.nio2.Nio2Session.handleReadCycleCompletion(Nio2Session.java:285) ~[sshd-core-1.2.0.jar:1.2.0]
	at org.apache.sshd.common.io.nio2.Nio2Session$2.onCompleted(Nio2Session.java:265) ~[sshd-core-1.2.0.jar:1.2.0]
	at org.apache.sshd.common.io.nio2.Nio2Session$2.onCompleted(Nio2Session.java:262) ~[sshd-core-1.2.0.jar:1.2.0]
	at org.apache.sshd.common.io.nio2.Nio2CompletionHandler$1.run(Nio2CompletionHandler.java:37) ~[sshd-core-1.2.0.jar:1.2.0]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_72]
	at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.completed(Nio2CompletionHandler.java:34) ~[sshd-core-1.2.0.jar:1.2.0]
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126) ~[na:1.8.0_72]
	at sun.nio.ch.Invoker$2.run(Invoker.java:218) ~[na:1.8.0_72]
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112) ~[na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72]
	... 1 common frames omitted

```

**Comment by K0zka** [comment]
no code modification needed, only sshd configuration change needed:
```
PermitRootLogin yes
PermitRootLogin without-password
```
