### ISSUE TITLE
bsd vmstat util breaks with freebsd 12

### ISSUE THREAD

**Issue by K0zka** [kerubistan/kerub#253]
```

   813	17:46:57.648 [sshd-SshClient[5c2f37ec]-nio2-thread-1] WARN  c.g.k.k.u.DefaultSshEventListener - session exception
   814	java.lang.IndexOutOfBoundsException: Index: 18, Size: 18
   815		at java.util.ArrayList.rangeCheck(ArrayList.java:657)
   816		at java.util.ArrayList.get(ArrayList.java:433)
   817		at com.github.kerubistan.kerub.utils.junix.vmstat.BsdVmStat$BsdVmstatOutputStream.handleInput(BsdVmStat.kt:15)
   818		at com.github.kerubistan.kerub.utils.junix.vmstat.AbstractVmstatOutputStream.write(AbstractVmstatOutputStream.kt:23)
   819		at java.io.OutputStream.write(OutputStream.java:116)
   820		at org.apache.sshd.client.channel.AbstractClientChannel.doWriteData(AbstractClientChannel.java:382)
   821		at org.apache.sshd.common.channel.AbstractChannel.handleData(AbstractChannel.java:821)
   822		at org.apache.sshd.common.session.helpers.AbstractConnectionService.channelData(AbstractConnectionService.java:442)
   823		at org.apache.sshd.common.session.helpers.AbstractConnectionService.process(AbstractConnectionService.java:344)
   824		at org.apache.sshd.common.session.helpers.AbstractSession.doHandleMessage(AbstractSession.java:614)
   825		at org.apache.sshd.common.session.helpers.AbstractSession.handleMessage(AbstractSession.java:547)
   826		at org.apache.sshd.common.session.helpers.AbstractSession.decode(AbstractSession.java:1498)
   827		at org.apache.sshd.common.session.helpers.AbstractSession.messageReceived(AbstractSession.java:508)
   828		at org.apache.sshd.common.session.helpers.AbstractSessionIoHandler.messageReceived(AbstractSessionIoHandler.java:66)
   829		at org.apache.sshd.common.io.nio2.Nio2Session.handleReadCycleCompletion(Nio2Session.java:301)
   830		at org.apache.sshd.common.io.nio2.Nio2Session$1.onCompleted(Nio2Session.java:281)
   831		at org.apache.sshd.common.io.nio2.Nio2Session$1.onCompleted(Nio2Session.java:278)
   832		at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.lambda$completed$0(Nio2CompletionHandler.java:38)
   833		at java.security.AccessController.doPrivileged(Native Method)
   834		at org.apache.sshd.common.io.nio2.Nio2CompletionHandler.completed(Nio2CompletionHandler.java:37)
   835		at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
```

found in test automatoin output

**Comment by K0zka** [comment]
And also gvinum, maybe others...

**Comment by K0zka** [comment]
reason for the vmstat pain: each disk is a column, so the hardcoded indexes do not work
