### ISSUE TITLE
lvm thin provisioning test fails

### ISSUE THREAD

**Issue by K0zka** [kerubistan/kerub#263]

**Comment by K0zka** [comment]
too much fun, on ubuntu thin-provisioning-tools is not part of the default install, therefore thin lvm creation fails with 
```
2625	06:34:28.149 [kovenant-callback-2] WARN  c.g.k.k.p.execution.PlanExecutorImpl - plan execution failed: [CreateLvmPool, CreateThinLv, KvmStartVirtualMachine]
  2626	at step:CreateThinLv
  2627	Plan(states=[OperationalState(hosts={3df2e77e-611e-43dc-8b72-854071f16423=HostDataCollection(stat=Host(id=3df2e77e-611e-43dc-8b72-854071f16423,addr=192.168.123.31), dynamic=HostDynamic(id=3df2e77e-611e-43dc-8b72-854071f16423, lastUpdated=1570271665580, status=Up, userCpu=2, systemCpu=0, idleCpu=80, memFree=1976582144, memUsed=113614848, memSwapped=0, ksmEnabled=false, cpuStats=[CpuStat(cpuNr=0, user=1.0, system=1.0, ioWait=15.0, idle=83.0)], storageStatus=[CompositeStorageDeviceDynamic(id=0af28889-5222-4a1f-ad12-c6ec999ca7d0, reportedFreeCapacity=1099507433472, items=[CompositeStorageDeviceDynamicItem(name=/dev/vdb, freeCapacity=1099507433472)], pools=[]), SimpleStorageDeviceDynamic(id=1586431f-fb5d-4004-b20b-d7d746754801, freeCapacity=1636843520)], storageDeviceHealth={}, cpuTemperature=[]), config=HostConfiguration(id=3df2e77e-611e-43dc-8b72-854071f16423, services=[], storageConfiguration=[], publicKey=null, acceptedPublicKeys=[]))}, vms={253fb474-fb9a-403a-803e-8fee8fce79b3=VirtualMachineDataCollection(stat=VM(id=253fb474-fb9a-403a-803e-8fee8fce79b3,name=vm-253fb474-fb9a-403a-803e-8fee8fce79b3exp=1), dynamic=null)}, vStorage={4566dea9-d125-429a-b59f-704afdcb2db4=VirtualStorageDataCollection(stat=VirtualStorageDevice(id=4566dea9-d125-429a-b59f-704afdcb2db4, size=18874368, readOnly=false, expectations=[], name=TinyCore-current.iso, owner=null, recycling=false), dynamic=VirtualStorageDeviceDynamic(id=4566dea9-d125-429a-b59f-704afdcb2db4, lastUpdated=1570271658968, allocations=[VirtualStorageLvmAllocation(hostId=3df2e77e-611e-43dc-8b72-854071f16423, capabilityId=0af28889-5222-4a1f-ad12-c6ec999ca7d0, actualSize=20971520, path=/dev/kerub-storage/4566dea9-d125-429a-b59f-704afdcb2db4, pool=null, vgName=kerub-storage, mirrors=0)])), 71a1bef8-fa7c-4530-9a54-a7a85dc21326=VirtualStorageDataCollection(stat=VirtualStorageDevice(id=71a1bef8-fa7c-4530-9a54-a7a85dc21326, size=4398046511104, readOnly=false, expectations=[], name=disk-71a1bef8-fa7c-4530-9a54-a7a85dc21326, owner=null, recycling=false), dynamic=null)}, vNet={}, pools={}, templates={}, reservations=[], controllerConfig=ControllerConfig(accountsRequired=false, powerManagementEnabled=true, wakeOnLanEnabled=false, ksmEnabled=true, installSoftwareEnabled=false, storageTechnologies=StorageTechnologiesConfig(fsPathEnabled=[/kerub, /storage], fsTypeEnabled=[ext4, ext3, zfs, btrfs, ufs], lvmCreateVolumeEnabled=true, lvmVGPattern=.*, gvinumCreateVolumeEnabled=true, cephEnabled=false, glusterEnabled=false, nfsEnabled=true, iscsiEnabled=true, storageBenchmarkingEnabled=false), maximumRedundancyAllowed=4, hypervisorTechnologies=HypervisorTechnologies(kvmEnabled=true, xenEnabled=false, bhyveEnabled=false, virtualBoxEnabled=false), archiverConfig=ArchiverConfig(compressDayJobCron=0 0 * * *, keepDays=7), cpuNormalTemperature=Range(min=20, max=70))), OperationalState(hosts={3df2e77e-611e-43dc-8b72-854071f16423=HostDataCollection(stat=Host(id=3df2e77e-611e-43dc-8b72-854071f16423,addr=192.168.123.31), dynamic=HostDynamic(id=3df2e77e-611e-43dc-8b72-854071f16423, lastUpdated=1570271665580, status=Up, userCpu=2, systemCpu=0, idleCpu=80, memFree=1976582144, memUsed=113614848, memSwapped=0, ksmEnabled=false, cpuStats=[CpuStat(cpuNr=0, user=1.0, system=1.0, ioWait=15.0, idle=83.0)], storageStatus=[CompositeStorageDeviceDynamic(id=0af28889-5222-4a1f-ad12-c6ec999ca7d0, reportedFreeCapacity=1088512359138, items=[CompositeStorageDeviceDynamicItem(name=/dev/vdb, freeCapacity=1099507433472)], pools=[]), SimpleStorageDeviceDynamic(id=1586431f-fb5d-4004-b20b-d7d746754801, freeCapacity=1636843520)], storageDeviceHealth={}, cpuTemperature=[]), config=HostConfiguration(id=3df2e77e-611e-43dc-8b72-854071f16423, services=[], storageConfiguration=[LvmPoolConfiguration(vgName=kerub-storage, poolName=6c220bda-9f15-4103-9288-ad989a63cf4a, size=10995074334)], publicKey=null, acceptedPublicKeys=[]))}, vms={253fb474-fb9a-403a-803e-8fee8fce79b3=VirtualMachineDataCollection(stat=VM(id=253fb474-fb9a-403a-803e-8fee8fce79b3,name=vm-253fb474-fb9a-403a-803e-8fee8fce79b3exp=1), dynamic=null)}, vStorage={4566dea9-d125-429a-b59f-704afdcb2db4=VirtualStorageDataCollection(stat=VirtualStorageDevice(id=4566dea9-d125-429a-b59f-704afdcb2db4, size=18874368, readOnly=false, expectations=[], name=TinyCore-current.iso, owner=null, recycling=false), dynamic=VirtualStorageDeviceDynamic(id=4566dea9-d125-429a-b59f-704afdcb2db4, lastUpdated=1570271658968, allocations=[VirtualStorageLvmAllocation(hostId=3df2e77e-611e-43dc-8b72-854071f16423, capabilityId=0af28889-5222-4a1f-ad12-c6ec999ca7d0, actualSize=20971520, path=/dev/kerub-storage/4566dea9-d125-429a-b59f-704afdcb2db4, pool=null, vgName=kerub-storage, mirrors=0)])), 71a1bef8-fa7c-4530-9a54-a7a85dc21326=VirtualStorageDataCollection(stat=VirtualStorageDevice(id=71a1bef8-fa7c-4530-9a54-a7a85dc21326, size=4398046511104, readOnly=false, expectations=[], name=disk-71a1bef8-fa7c-4530-9a54-a7a85dc21326, owner=null, recycling=false), dynamic=null)}, vNet={}, pools={}, templates={}, reservations=[], controllerConfig=ControllerConfig(accountsRequired=false, powerManagementEnabled=true, wakeOnLanEnabled=false, ksmEnabled=true, installSoftwareEnabled=false, storageTechnologies=StorageTechnologiesConfig(fsPathEnabled=[/kerub, /storage], fsTypeEnabled=[ext4, ext3, zfs, btrfs, ufs], lvmCreateVolumeEnabled=true, lvmVGPattern=.*, gvinumCreateVolumeEnabled=true, cephEnabled=false, glusterEnabled=false, nfsEnabled=true, iscsiEnabled=true, storageBenchmarkingEnabled=false), maximumRedundancyAllowed=4, hypervisorTechnologies=HypervisorTechnologies(kvmEnabled=true, xenEnabled=false, bhyveEnabled=false, virtualBoxEnabled=false), archiverConfig=ArchiverConfig(compressDayJobCron=0 0 * * *, keepDays=7), cpuNormalTemperature=Range(min=20, max=70))), OperationalState(hosts={3df2e77e-611e-43dc-8b72-854071f16423=HostDataCollection(stat=Host(id=3df2e77e-611e-43dc-8b72-854071f16423,addr=192.168.123.31), dynamic=HostDynamic(id=3df2e77e-611e-43dc-8b72-854071f16423, lastUpdated=1570271665580, status=Up, userCpu=2, systemCpu=0, idleCpu=80, memFree=1976582144, memUsed=113614848, memSwapped=0, ksmEnabled=false, cpuStats=[CpuStat(cpuNr=0, user=1.0, system=1.0, ioWait=15.0, idle=83.0)], storageStatus=[CompositeStorageDeviceDynamic(id=0af28889-5222-4a1f-ad12-c6ec999ca7d0, reportedFreeCapacity=1088512359138, items=[CompositeStorageDeviceDynamicItem(name=/dev/vdb, freeCapacity=1099507433472)], pools=[]), SimpleStorageDeviceDynamic(id=1586431f-fb5d-4004-b20b-d7d746754801, freeCapacity=1636843520)], storageDeviceHealth={}, cpuTemperature=[]), config=HostConfiguration(id=3df2e77e-611e-43dc-8b72-854071f16423, services=[], storageConfiguration=[LvmPoolConfiguration(vgName=kerub-storage, poolName=6c220bda-9f15-4103-9288-ad989a63cf4a, size=10995074334)], publicKey=null, acceptedPublicKeys=[]))}, vms={253fb474-fb9a-403a-803e-8fee8fce79b3=VirtualMachineDataCollection(stat=VM(id=253fb474-fb9a-403a-803e-8fee8fce79b3,name=vm-253fb474-fb9a-403a-803e-8fee8fce79b3exp=1), dynamic=null)}, vStorage={4566dea9-d125-429a-b59f-704afdcb2db4=VirtualStorageDataCollection(stat=VirtualStorageDevice(id=4566dea9-d125-429a-b59f-704afdcb2db4, size=18874368, readOnly=false, expectations=[], name=TinyCore-current.iso, owner=null, recycling=false), dynamic=VirtualStorageDeviceDynamic(id=4566dea9-d125-429a-b59f-704afdcb2db4, lastUpdated=1570271658968, allocations=[VirtualStorageLvmAllocation(hostId=3df2e77e-611e-43dc-8b72-854071f16423, capabilityId=0af28889-5222-4a1f-ad12-c6ec999ca7d0, actualSize=20971520, path=/dev/kerub-storage/4566dea9-d125-429a-b59f-704afdcb2db4, pool=null, vgName=kerub-storage, mirrors=0)])), 71a1bef8-fa7c-4530-9a54-a7a85dc21326=VirtualStorageDataCollection(stat=VirtualStorageDevice(id=71a1bef8-fa7c-4530-9a54-a7a85dc21326, size=4398046511104, readOnly=false, expectations=[], name=disk-71a1bef8-fa7c-4530-9a54-a7a85dc21326, owner=null, recycling=false), dynamic=VirtualStorageDeviceDynamic(id=71a1bef8-fa7c-4530-9a54-a7a85dc21326, lastUpdated=1570271665700, allocations=[VirtualStorageLvmAllocation(hostId=3df2e77e-611e-43dc-8b72-854071f16423, capabilityId=0af28889-5222-4a1f-ad12-c6ec999ca7d0, actualSize=0, path=, pool=6c220bda-9f15-4103-9288-ad989a63cf4a, vgName=kerub-storage, mirrors=0)]))}, vNet={}, pools={}, templates={}, reservations=[], controllerConfig=ControllerConfig(accountsRequired=false, powerManagementEnabled=true, wakeOnLanEnabled=false, ksmEnabled=true, installSoftwareEnabled=false, storageTechnologies=StorageTechnologiesConfig(fsPathEnabled=[/kerub, /storage], fsTypeEnabled=[ext4, ext3, zfs, btrfs, ufs], lvmCreateVolumeEnabled=true, lvmVGPattern=.*, gvinumCreateVolumeEnabled=true, cephEnabled=false, glusterEnabled=false, nfsEnabled=true, iscsiEnabled=true, storageBenchmarkingEnabled=false), maximumRedundancyAllowed=4, hypervisorTechnologies=HypervisorTechnologies(kvmEnabled=true, xenEnabled=false, bhyveEnabled=false, virtualBoxEnabled=false), archiverConfig=ArchiverConfig(compressDayJobCron=0 0 * * *, keepDays=7), cpuNormalTemperature=Range(min=20, max=70))), OperationalState(hosts={3df2e77e-611e-43dc-8b72-854071f16423=HostDataCollection(stat=Host(id=3df2e77e-611e-43dc-8b72-854071f16423,addr=192.168.123.31), dynamic=HostDynamic(id=3df2e77e-611e-43dc-8b72-854071f16423, lastUpdated=1570271665580, status=Up, userCpu=2, systemCpu=0, idleCpu=80, memFree=1976582144, memUsed=113614848, memSwapped=0, ksmEnabled=false, cpuStats=[CpuStat(cpuNr=0, user=1.0, system=1.0, ioWait=15.0, idle=83.0)], storageStatus=[CompositeStorageDeviceDynamic(id=0af28889-5222-4a1f-ad12-c6ec999ca7d0, reportedFreeCapacity=1088512359138, items=[CompositeStorageDeviceDynamicItem(name=/dev/vdb, freeCapacity=1099507433472)], pools=[]), SimpleStorageDeviceDynamic(id=1586431f-fb5d-4004-b20b-d7d746754801, freeCapacity=1636843520)], storageDeviceHealth={}, cpuTemperature=[]), config=HostConfiguration(id=3df2e77e-611e-43dc-8b72-854071f16423, services=[], storageConfiguration=[LvmPoolConfiguration(vgName=kerub-storage, poolName=6c220bda-9f15-4103-9288-ad989a63cf4a, size=10995074334)], publicKey=null, acceptedPublicKeys=[]))}, vms={253fb474-fb9a-403a-803e-8fee8fce79b3=VirtualMachineDataCollection(stat=VM(id=253fb474-fb9a-403a-803e-8fee8fce79b3,name=vm-253fb474-fb9a-403a-803e-8fee8fce79b3exp=1), dynamic=VirtualMachineDynamic(id=253fb474-fb9a-403a-803e-8fee8fce79b3, lastUpdated=1570271665752, hostId=3df2e77e-611e-43dc-8b72-854071f16423, status=Up, memoryUsed=1073741824, cpuUsage=[], displaySetting=null, coreAffinity=null))}, vStorage={4566dea9-d125-429a-b59f-704afdcb2db4=VirtualStorageDataCollection(stat=VirtualStorageDevice(id=4566dea9-d125-429a-b59f-704afdcb2db4, size=18874368, readOnly=false, expectations=[], name=TinyCore-current.iso, owner=null, recycling=false), dynamic=VirtualStorageDeviceDynamic(id=4566dea9-d125-429a-b59f-704afdcb2db4, lastUpdated=1570271658968, allocations=[VirtualStorageLvmAllocation(hostId=3df2e77e-611e-43dc-8b72-854071f16423, capabilityId=0af28889-5222-4a1f-ad12-c6ec999ca7d0, actualSize=20971520, path=/dev/kerub-storage/4566dea9-d125-429a-b59f-704afdcb2db4, pool=null, vgName=kerub-storage, mirrors=0)])), 71a1bef8-fa7c-4530-9a54-a7a85dc21326=VirtualStorageDataCollection(stat=VirtualStorageDevice(id=71a1bef8-fa7c-4530-9a54-a7a85dc21326, size=4398046511104, readOnly=false, expectations=[], name=disk-71a1bef8-fa7c-4530-9a54-a7a85dc21326, owner=null, recycling=false), dynamic=VirtualStorageDeviceDynamic(id=71a1bef8-fa7c-4530-9a54-a7a85dc21326, lastUpdated=1570271665700, allocations=[VirtualStorageLvmAllocation(hostId=3df2e77e-611e-43dc-8b72-854071f16423, capabilityId=0af28889-5222-4a1f-ad12-c6ec999ca7d0, actualSize=0, path=, pool=6c220bda-9f15-4103-9288-ad989a63cf4a, vgName=kerub-storage, mirrors=0)]))}, vNet={}, pools={}, templates={}, reservations=[], controllerConfig=ControllerConfig(accountsRequired=false, powerManagementEnabled=true, wakeOnLanEnabled=false, ksmEnabled=true, installSoftwareEnabled=false, storageTechnologies=StorageTechnologiesConfig(fsPathEnabled=[/kerub, /storage], fsTypeEnabled=[ext4, ext3, zfs, btrfs, ufs], lvmCreateVolumeEnabled=true, lvmVGPattern=.*, gvinumCreateVolumeEnabled=true, cephEnabled=false, glusterEnabled=false, nfsEnabled=true, iscsiEnabled=true, storageBenchmarkingEnabled=false), maximumRedundancyAllowed=4, hypervisorTechnologies=HypervisorTechnologies(kvmEnabled=true, xenEnabled=false, bhyveEnabled=false, virtualBoxEnabled=false), archiverConfig=ArchiverConfig(compressDayJobCron=0 0 * * *, keepDays=7), cpuNormalTemperature=Range(min=20, max=70)))], steps=[CreateLvmPool(host=Host(id=3df2e77e-611e-43dc-8b72-854071f16423,addr=192.168.123.31), vgName=kerub-storage, name=6c220bda-9f15-4103-9288-ad989a63cf4a, size=10995074334), CreateThinLv(host=Host(id=3df2e77e-611e-43dc-8b72-854071f16423,addr=192.168.123.31), capability=LvmStorageCapability(id=0af28889-5222-4a1f-ad12-c6ec999ca7d0, size=1099507433472, volumeGroupName=kerub-storage, physicalVolumes={/dev/vdb=1099507433472}, performanceInfo=null), disk=VirtualStorageDevice(id=71a1bef8-fa7c-4530-9a54-a7a85dc21326, size=4398046511104, readOnly=false, expectations=[], name=disk-71a1bef8-fa7c-4530-9a54-a7a85dc21326, owner=null, recycling=false), poolName=6c220bda-9f15-4103-9288-ad989a63cf4a), KvmStartVirtualMachine(vm=VM(id=253fb474-fb9a-403a-803e-8fee8fce79b3,name=vm-253fb474-fb9a-403a-803e-8fee8fce79b3exp=1), host=Host(id=3df2e77e-611e-43dc-8b72-854071f16423,addr=192.168.123.31), storageLinks=[VirtualStorageLinkInfo(link=VirtualStorageLink(virtualStorageId=4566dea9-d125-429a-b59f-704afdcb2db4, bus=sata, expectations=[], device=cdrom, readOnly=false), device=VirtualStorageDataCollection(stat=VirtualStorageDevice(id=4566dea9-d125-429a-b59f-704afdcb2db4, size=18874368, readOnly=false, expectations=[], name=TinyCore-current.iso, owner=null, recycling=false), dynamic=VirtualStorageDeviceDynamic(id=4566dea9-d125-429a-b59f-704afdcb2db4, lastUpdated=1570271658968, allocations=[VirtualStorageLvmAllocation(hostId=3df2e77e-611e-43dc-8b72-854071f16423, capabilityId=0af28889-5222-4a1f-ad12-c6ec999ca7d0, actualSize=20971520, path=/dev/kerub-storage/4566dea9-d125-429a-b59f-704afdcb2db4, pool=null, vgName=kerub-storage, mirrors=0)])), allocation=VirtualStorageLvmAllocation(hostId=3df2e77e-611e-43dc-8b72-854071f16423, capabilityId=0af28889-5222-4a1f-ad12-c6ec999ca7d0, actualSize=20971520, path=/dev/kerub-storage/4566dea9-d125-429a-b59f-704afdcb2db4, pool=null, vgName=kerub-storage, mirrors=0), hostServiceUsed=null, storageHost=HostDataCollection(stat=Host(id=3df2e77e-611e-43dc-8b72-854071f16423,addr=192.168.123.31), dynamic=HostDynamic(id=3df2e77e-611e-43dc-8b72-854071f16423, lastUpdated=1570271665580, status=Up, userCpu=2, systemCpu=0, idleCpu=80, memFree=1976582144, memUsed=113614848, memSwapped=0, ksmEnabled=false, cpuStats=[CpuStat(cpuNr=0, user=1.0, system=1.0, ioWait=15.0, idle=83.0)], storageStatus=[CompositeStorageDeviceDynamic(id=0af28889-5222-4a1f-ad12-c6ec999ca7d0, reportedFreeCapacity=1088512359138, items=[CompositeStorageDeviceDynamicItem(name=/dev/vdb, freeCapacity=1099507433472)], pools=[]), SimpleStorageDeviceDynamic(id=1586431f-fb5d-4004-b20b-d7d746754801, freeCapacity=1636843520)], storageDeviceHealth={}, cpuTemperature=[]), config=HostConfiguration(id=3df2e77e-611e-43dc-8b72-854071f16423, services=[], storageConfiguration=[LvmPoolConfiguration(vgName=kerub-storage, poolName=6c220bda-9f15-4103-9288-ad989a63cf4a, size=10995074334)], publicKey=null, acceptedPublicKeys=[]))), VirtualStorageLinkInfo(link=VirtualStorageLink(virtualStorageId=71a1bef8-fa7c-4530-9a54-a7a85dc21326, bus=virtio, expectations=[], device=disk, readOnly=false), device=VirtualStorageDataCollection(stat=VirtualStorageDevice(id=71a1bef8-fa7c-4530-9a54-a7a85dc21326, size=4398046511104, readOnly=false, expectations=[], name=disk-71a1bef8-fa7c-4530-9a54-a7a85dc21326, owner=null, recycling=false), dynamic=VirtualStorageDeviceDynamic(id=71a1bef8-fa7c-4530-9a54-a7a85dc21326, lastUpdated=1570271665700, allocations=[VirtualStorageLvmAllocation(hostId=3df2e77e-611e-43dc-8b72-854071f16423, capabilityId=0af28889-5222-4a1f-ad12-c6ec999ca7d0, actualSize=0, path=, pool=6c220bda-9f15-4103-9288-ad989a63cf4a, vgName=kerub-storage, mirrors=0)])), allocation=VirtualStorageLvmAllocation(hostId=3df2e77e-611e-43dc-8b72-854071f16423, capabilityId=0af28889-5222-4a1f-ad12-c6ec999ca7d0, actualSize=0, path=, pool=6c220bda-9f15-4103-9288-ad989a63cf4a, vgName=kerub-storage, mirrors=0), hostServiceUsed=null, storageHost=HostDataCollection(stat=Host(id=3df2e77e-611e-43dc-8b72-854071f16423,addr=192.168.123.31), dynamic=HostDynamic(id=3df2e77e-611e-43dc-8b72-854071f16423, lastUpdated=1570271665580, status=Up, userCpu=2, systemCpu=0, idleCpu=80, memFree=1976582144, memUsed=113614848, memSwapped=0, ksmEnabled=false, cpuStats=[CpuStat(cpuNr=0, user=1.0, system=1.0, ioWait=15.0, idle=83.0)], storageStatus=[CompositeStorageDeviceDynamic(id=0af28889-5222-4a1f-ad12-c6ec999ca7d0, reportedFreeCapacity=1088512359138, items=[CompositeStorageDeviceDynamicItem(name=/dev/vdb, freeCapacity=1099507433472)], pools=[]), SimpleStorageDeviceDynamic(id=1586431f-fb5d-4004-b20b-d7d746754801, freeCapacity=1636843520)], storageDeviceHealth={}, cpuTemperature=[]), config=HostConfiguration(id=3df2e77e-611e-43dc-8b72-854071f16423, services=[], storageConfiguration=[LvmPoolConfiguration(vgName=kerub-storage, poolName=6c220bda-9f15-4103-9288-ad989a63cf4a, size=10995074334)], publicKey=null, acceptedPublicKeys=[])))])])
  2628	java.io.IOException:   /usr/sbin/thin_check: execvp failed: No such file or directory
  2629	  WARNING: Integrity check of metadata for pool kerub-storage/6c220bda-9f15-4103-9288-ad989a63cf4a failed.
  2630	  WARNING: Sum of all thin volume sizes (4.00 TiB) exceeds the size of thin pool kerub-storage/6c220bda-9f15-4103-9288-ad989a63cf4a and the size of whole volume group (<1024.00 GiB).
  2631	  /usr/sbin/thin_check: execvp failed: No such file or directory
  2632	  Check of pool kerub-storage/6c220bda-9f15-4103-9288-ad989a63cf4a failed (status:2). Manual repair required!
  2633	  Failed to activate thin pool kerub-storage/6c220bda-9f15-4103-9288-ad989a63cf4a.
  2634	
  2635		at com.github.kerubistan.kerub.host.SshClientUtilsKt$executeOrDie$2.invoke(SshClientUtils.kt:99)
  2636		at com.github.kerubistan.kerub.host.SshClientUtilsKt$executeOrDie$2.invoke(SshClientUtils.kt)
  2637		at com.github.kerubistan.kerub.host.SshClientUtilsKt.use(SshClientUtils.kt:41)
  2638		at com.github.kerubistan.kerub.host.SshClientUtilsKt.executeOrDie(SshClientUtils.kt:95)
  2639		at com.github.kerubistan.kerub.host.SshClientUtilsKt.executeOrDie$default(SshClientUtils.kt:93)
  2640		at com.github.kerubistan.kerub.utils.junix.storagemanager.lvm.LvmLv.create(LvmLv.kt:168)
  2641		at com.github.kerubistan.kerub.utils.junix.storagemanager.lvm.LvmLv.create$default(LvmLv.kt:149)
  2642		at com.github.kerubistan.kerub.planner.steps.storage.lvm.create.CreateThinLvExecutor$perform$1.invoke(CreateThinLvExecutor.kt:15)
  2643		at com.github.kerubistan.kerub.planner.steps.storage.lvm.create.CreateThinLvExecutor$perform$1.invoke(CreateThinLvExecutor.kt:8)
  2644		at com.github.kerubistan.kerub.host.HostManagerImpl.execute(HostManagerImpl.kt:82)

```

but it depends on the lvm configuration...
